### ISSUE TITLE
Good work

### ISSUE THREAD

**Issue by bradherman** [davidrunger/active_actions#362]
Love it dude!  Might move from interactors to this.  Only suggestion would be to find a way to add a mechanism for chaining actions, like the Organizer pattern in interactor-rails

**Comment by davidrunger** [comment]
Hey @bradherman ! Great to hear from you. I hope that you are doing well!

> Only suggestion would be to find a way to add a mechanism for chaining actions, like the Organizer pattern in interactor-rails

Thanks! That is an absolutely on-point suggestion! I basically built this `active_actions` gem for use in https://github.com/davidrunger/david_runger/ , and that app is simple enough that I haven't had many use-cases for chaining actions together, but that's definitely a missing feature with respect to meeting the full possible scope of functionality for a library like this! I did once have a place in that app where I manually "chained" together a few different actions (see the now-deleted code [here](https://github.com/davidrunger/david_runger/blob/86823b8633e4fff86093481709dd9fc3d64cfb26/app/actions/sms_records/send_message.rb), which manually chained together the `SmsRecords::GenerateMessage`, `SmsRecords::PostToNexmo`, and `SmsRecords::SaveSmsRecord` actions), but I have since deleted that code, and so I don't have a first-hand use case for chaining actions, so I haven't been motivated to add it to `active_actions`. But you're 💯% right that it's a missing feature that would be great to add to make this library really properly full-featured!

Speaking of which, you'd probably do better to stick with one of the more widely used solutions like `interactor-rails` that you mentioned or any of the others that I mentioned in the "[Alternatives](https://github.com/davidrunger/active_actions#alternatives)" section of the `active_actions` README.

But thanks for checking out this little experimental library of mine and leaving your feedback! Great to hear from you!
